version: 0.2
phases:
   pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u AWS ---password-stdin $(aws ecr get-login-password --region ap-south-1) 019523160407.dkr.ecr.ap-south-1.amazonaws.com
      - aws --version
   build:
    commands:
      - echo Building the Docker image...
      - docker build -t secondweb .
      - docker tag secondweb:latest 019523160407.dkr.ecr.ap-south-1.amazonaws.com/secondweb:latest
   post_build:
    commands:
      - echo Build completed on 'date'
      - echo pushing the docker images...
      - docker push 019523160407.dkr.ecr.ap-south-1.amazonaws.com/secondweb:latest
      - echo writting docker image defination file...
